using UnityEngine;
using static Defines;

public static class CreateHeroEnemy
{

    public static HeroEnemy GenarateHero()
    {
        HeroEnemy hE = new HeroEnemy();
        hE.nameHeroEnemy = "Труп";
        hE.PARAMS[ARENA_ENEMY_EXP] = 5;
        hE.PARAMS[ARENA_ENEMY_LEVEL] = 5;
        hE.PARAMS[ARENA_ENEMY_VIP_EXP] = 5;
        hE.PARAMS[ARENA_ENEMY_VIP_LEVEL] = 5;
        hE.PARAMS[ARENA_ENEMY_HP] = 100;
        hE.PARAMS[ARENA_ENEMY_MANA] = 5;
        hE.PARAMS[ARENA_ENEMY_DAMAGE] = 5;
        hE.PARAMS[ARENA_ENEMY_DAMAGE_ICE] = 5;
        hE.PARAMS[ARENA_ENEMY_DAMAGE_FIRE] = 5;
        hE.PARAMS[ARENA_ENEMY_DAMAGE_ELECTRIC] = 5;
        hE.PARAMS[ARENA_ENEMY_STRENGTH] = 5;
        hE.PARAMS[ARENA_ENEMY_AGILITY] = 5;
        hE.PARAMS[ARENA_ENEMY_INTELLECT] = 5;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_HEAD] = 5;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_TORS] = 5;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_PANTS] = 5;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_BOTS] = 5;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_ICE] = 5;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_FIRE] = 5;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_ELECTRIC] = 5;
        hE.PARAMS[ARENA_ENEMY_AP_ATTACK] = 5;
        hE.PARAMS[ARENA_ENEMY_AP_DEFENSE] = 5;
        hE.PARAMS[ARENA_ENEMY_EVASION] = 5;
        hE.PARAMS[ARENA_ENEMY_BLOCK] = 5;
        hE.PARAMS[ARENA_ENEMY_ACCURACY] = 5;
        hE.PARAMS[ARENA_ENEMY_CRIT_DAMAGE] = 5;
        hE.PARAMS[ARENA_ENEMY_CRIT_CHANGE] = 5;
        hE.PARAMS[ARENA_ENEMY_PARRY] = Hero.PARAMS[ARENA_HERO_PARRY] + Mathf.RoundToInt(Random.Range(Hero.PARAMS[ARENA_HERO_HP] / -5, Hero.PARAMS[ARENA_HERO_HP] / 10));

        hE.PARAMS[ARENA_ENEMY_HP_CURRENT] = hE.PARAMS[ARENA_ENEMY_HP];
        hE.PARAMS[ARENA_ENEMY_MANA_CURRENT] = hE.PARAMS[ARENA_ENEMY_MANA];
        hE.PARAMS[ARENA_ENEMY_DAMAGE_CURRENT] = hE.PARAMS[ARENA_ENEMY_DAMAGE];
        hE.PARAMS[ARENA_ENEMY_DAMAGE_ICE_CURRENT] = hE.PARAMS[ARENA_ENEMY_DAMAGE_ICE];
        hE.PARAMS[ARENA_ENEMY_DAMAGE_FIRE_CURRENT] = hE.PARAMS[ARENA_ENEMY_DAMAGE_FIRE];
        hE.PARAMS[ARENA_ENEMY_DAMAGE_ELECTRIC_CURRENT] = hE.PARAMS[ARENA_ENEMY_DAMAGE_ELECTRIC];
        hE.PARAMS[ARENA_ENEMY_STRENGTH_CURRENT] = hE.PARAMS[ARENA_ENEMY_STRENGTH];
        hE.PARAMS[ARENA_ENEMY_AGILITY_CURRENT] = hE.PARAMS[ARENA_ENEMY_AGILITY];
        hE.PARAMS[ARENA_ENEMY_INTELLECT_CURRENT] = hE.PARAMS[ARENA_ENEMY_INTELLECT];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_HEAD_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_HEAD];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_TORS_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_TORS];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_PANTS_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_PANTS];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_BOTS_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_BOTS];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_ICE_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_ICE];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_FIRE_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_FIRE];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_ELECTRIC_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_ELECTRIC];
        hE.PARAMS[ARENA_ENEMY_AP_ATTACK_CURRENT] = hE.PARAMS[ARENA_ENEMY_AP_ATTACK];
        hE.PARAMS[ARENA_ENEMY_AP_DEFENSE_CURRENT] = hE.PARAMS[ARENA_ENEMY_AP_DEFENSE];
        hE.PARAMS[ARENA_ENEMY_EVASION_CURRENT] = hE.PARAMS[ARENA_ENEMY_EVASION];
        hE.PARAMS[ARENA_ENEMY_BLOCK_CURRENT] = hE.PARAMS[ARENA_ENEMY_BLOCK];
        hE.PARAMS[ARENA_ENEMY_ACCURACY_CURRENT] = hE.PARAMS[ARENA_ENEMY_ACCURACY];
        hE.PARAMS[ARENA_ENEMY_CRIT_DAMAGE_CURRENT] = hE.PARAMS[ARENA_ENEMY_CRIT_DAMAGE];
        hE.PARAMS[ARENA_ENEMY_CRIT_CHANGE_CURRENT] = hE.PARAMS[ARENA_ENEMY_CRIT_CHANGE];
        hE.PARAMS[ARENA_ENEMY_PARRY_CURRENT] = hE.PARAMS[ARENA_ENEMY_PARRY];

        return hE;
    }

    public static HeroEnemy GenarateHeroAdvanced()
    {
        HeroEnemy hE = new HeroEnemy();
        hE.nameHeroEnemy = "Труп";
        hE.PARAMS[ARENA_ENEMY_EXP] = 15;
        hE.PARAMS[ARENA_ENEMY_LEVEL] = 15;
        hE.PARAMS[ARENA_ENEMY_VIP_EXP] = 15;
        hE.PARAMS[ARENA_ENEMY_VIP_LEVEL] = 15;
        hE.PARAMS[ARENA_ENEMY_HP] = 15;
        hE.PARAMS[ARENA_ENEMY_MANA] = 15;
        hE.PARAMS[ARENA_ENEMY_DAMAGE] = 15;
        hE.PARAMS[ARENA_ENEMY_DAMAGE_ICE] = 15;
        hE.PARAMS[ARENA_ENEMY_DAMAGE_FIRE] = 15;
        hE.PARAMS[ARENA_ENEMY_DAMAGE_ELECTRIC] = 15;
        hE.PARAMS[ARENA_ENEMY_STRENGTH] = 15;
        hE.PARAMS[ARENA_ENEMY_AGILITY] = 15;
        hE.PARAMS[ARENA_ENEMY_INTELLECT] = 15;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_HEAD] = 15;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_TORS] = 15;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_PANTS] = 15;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_BOTS] = 15;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_ICE] = 15;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_FIRE] = 15;
        hE.PARAMS[ARENA_ENEMY_DEFENSE_ELECTRIC] = 15;
        hE.PARAMS[ARENA_ENEMY_AP_ATTACK] = 15;
        hE.PARAMS[ARENA_ENEMY_AP_DEFENSE] = 15;
        hE.PARAMS[ARENA_ENEMY_EVASION] = 15;
        hE.PARAMS[ARENA_ENEMY_BLOCK] = 15;
        hE.PARAMS[ARENA_ENEMY_ACCURACY] = 15;
        hE.PARAMS[ARENA_ENEMY_CRIT_DAMAGE] = 15;
        hE.PARAMS[ARENA_ENEMY_CRIT_CHANGE] = 15;
        hE.PARAMS[ARENA_ENEMY_PARRY] = Hero.PARAMS[ARENA_HERO_PARRY] + Mathf.RoundToInt(Random.Range(Hero.PARAMS[ARENA_HERO_HP] / -5, Hero.PARAMS[ARENA_HERO_HP] / 10));

        hE.PARAMS[ARENA_ENEMY_HP_CURRENT] = hE.PARAMS[ARENA_ENEMY_HP];
        hE.PARAMS[ARENA_ENEMY_MANA_CURRENT] = hE.PARAMS[ARENA_ENEMY_MANA];
        hE.PARAMS[ARENA_ENEMY_DAMAGE_CURRENT] = hE.PARAMS[ARENA_ENEMY_DAMAGE];
        hE.PARAMS[ARENA_ENEMY_DAMAGE_ICE_CURRENT] = hE.PARAMS[ARENA_ENEMY_DAMAGE_ICE];
        hE.PARAMS[ARENA_ENEMY_DAMAGE_FIRE_CURRENT] = hE.PARAMS[ARENA_ENEMY_DAMAGE_FIRE];
        hE.PARAMS[ARENA_ENEMY_DAMAGE_ELECTRIC_CURRENT] = hE.PARAMS[ARENA_ENEMY_DAMAGE_ELECTRIC];
        hE.PARAMS[ARENA_ENEMY_STRENGTH_CURRENT] = hE.PARAMS[ARENA_ENEMY_STRENGTH];
        hE.PARAMS[ARENA_ENEMY_AGILITY_CURRENT] = hE.PARAMS[ARENA_ENEMY_AGILITY];
        hE.PARAMS[ARENA_ENEMY_INTELLECT_CURRENT] = hE.PARAMS[ARENA_ENEMY_INTELLECT];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_HEAD_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_HEAD];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_TORS_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_TORS];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_PANTS_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_PANTS];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_BOTS_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_BOTS];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_ICE_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_ICE];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_FIRE_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_FIRE];
        hE.PARAMS[ARENA_ENEMY_DEFENSE_ELECTRIC_CURRENT] = hE.PARAMS[ARENA_ENEMY_DEFENSE_ELECTRIC];
        hE.PARAMS[ARENA_ENEMY_AP_ATTACK_CURRENT] = hE.PARAMS[ARENA_ENEMY_AP_ATTACK];
        hE.PARAMS[ARENA_ENEMY_AP_DEFENSE_CURRENT] = hE.PARAMS[ARENA_ENEMY_AP_DEFENSE];
        hE.PARAMS[ARENA_ENEMY_EVASION_CURRENT] = hE.PARAMS[ARENA_ENEMY_EVASION];
        hE.PARAMS[ARENA_ENEMY_BLOCK_CURRENT] = hE.PARAMS[ARENA_ENEMY_BLOCK];
        hE.PARAMS[ARENA_ENEMY_ACCURACY_CURRENT] = hE.PARAMS[ARENA_ENEMY_ACCURACY];
        hE.PARAMS[ARENA_ENEMY_CRIT_DAMAGE_CURRENT] = hE.PARAMS[ARENA_ENEMY_CRIT_DAMAGE];
        hE.PARAMS[ARENA_ENEMY_CRIT_CHANGE_CURRENT] = hE.PARAMS[ARENA_ENEMY_CRIT_CHANGE];
        hE.PARAMS[ARENA_ENEMY_PARRY_CURRENT] = hE.PARAMS[ARENA_ENEMY_PARRY];

        return hE;
    }

}
