using System.Collections.Generic;

public static class CreateGeneralEnemy
{
    public static List<General> CreateEnemy(string levelName, int wave)
    {
        List<General> generals = new List<General>();
        General g;
        switch (levelName)
        {
            case "V0":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V1":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V2":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(3);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V3":
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(3);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(4);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(4);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(3);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V4":
                g = CreateGeneral.GeneralEasy(4);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(4);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(4);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(4);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(4);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(4);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V5":
                g = CreateGeneral.GeneralEasy(9);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(9);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(10);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(10);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(9);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(9);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V6":
                g = CreateGeneral.GeneralEasy(15);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(15);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(15);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(15);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(15);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(15);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V7":
                g = CreateGeneral.GeneralEasy(10);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(15);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(20);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(20);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(15);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(10);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V8":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V9":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V10":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V11":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V12":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V13":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V14":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V15":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V16":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V17":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "V18":
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(1);
                SetParams(g, 0);
                generals.Add(g);
                g = CreateGeneral.GeneralEasy(2);
                SetParams(g, 0);
                generals.Add(g);
                break;
            case "C1":
                switch (wave)
                {
                    case 0:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                    case 1:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                    case 2:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                }
                break;
            case "C2":
                switch (wave)
                {
                    case 0:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                    case 1:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                    case 2:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                }
                break;
            case "C3":
                switch (wave)
                {
                    case 0:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                    case 1:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                    case 2:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                }
                break;
            case "C4":
                switch (wave)
                {
                    case 0:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                    case 1:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                    case 2:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                }
                break;
            case "C5":
                switch (wave)
                {
                    case 0:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                    case 1:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                    case 2:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                }
                break;
            case "C6":
                switch (wave)
                {
                    case 0:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                    case 1:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                    case 2:
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(1);
                        SetParams(g, 0);
                        generals.Add(g);
                        g = CreateGeneral.GeneralEasy(2);
                        SetParams(g, 0);
                        generals.Add(g);
                        break;
                }
                break;
        }
        return generals;
    }

    static void SetParams(General g, int n)
    {
        g.nameGeneral = GeneralText.GetName(n);
        g.descGeneral = GeneralText.GetDescription(n);
        g.prefab = ResManager.instance.gensE[n];
        g.img = ResManager.instance.genEImg[n];
        g.img2 = ResManager.instance.genEImg2[n];
    }
}
